apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-logs
spec:

  version: 8.4.1
  auth:
    fileRealm:
      - secretName: company-elasticsearch-users-roles
    roles:
      - secretName: company-elasticsearch-roles
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch-logs
    logs:
      elasticsearchRefs:
        - name: elasticsearch-logs
  nodeSets:
    - name: master-nodes
      count: 1
      config:
        node.roles: [ "master" ]
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi

    - name: data-nodes
      count: 2
      config:
        node.roles: [ "data","ingest" ]
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
