resources:
  - ../nginx-sample-app

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx
      namespace: default
    path: annotations-logs-patch.yaml

          
