apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default-log
spec:
  selector:
    matchLabels:
      app: nginx
      log: default-log
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
      labels:
        app: nginx
        log: default-log
    spec:
      containers:
        - name: nginx-default-log
          image: nginx:1.14.2
          ports:
            - containerPort: 80